# Generated by Django 5.0 on 2026-08-15 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('terminal', models.CharField(default='T1', max_length=20)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gate',
                'verbose_name_plural': 'Gates',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=20)),
                ('destination', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('SCHEDULED', 'SCHEDULED'), ('BOARDING', 'BOARDING'), ('DEPARTED', 'DEPARTED'), ('DELAYED', 'DELAYED'), ('CANCELLED', 'CANCELLED')], default='SCHEDULED', max_length=20)),
                ('departure_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gate_id', models.ForeignKey(db_column='gate_id', on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='aeropuerto.gates')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
    ]

